ALTER TABLE admins
MODIFY COLUMN PASSWORD VARCHAR(255)

ALTER TABLE new_volunteers
MODIFY COLUMN PASSWORD VARCHAR(255)

ALTER TABLE volunteers
MODIFY COLUMN PASSWORD VARCHAR(255)

-- add blocked
ALTER TABLE volunteers
ADD blocked VARCHAR(10);

ALTER TABLE users
ADD blocked VARCHAR(10);
